spring:
  application:
    name: digital-wallet-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/digital-wallet

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  admin:
    username: ${APP_ADMIN_USERNAME:admin}
    password: ${APP_ADMIN_PASSWORD}
    email: ${APP_ADMIN_EMAIL:admin@digitalwallet.com}
